# Generated by Django 4.2.16 on 2024-11-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0004_alter_agenda_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
