databases:
  - name: mysitedb
    plan: free
    databaseName: photo_app
    user: mysite

services:
  - type: web
    plan: free
    name: photo_app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn photo_app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: photo_app
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4